from collections.abc import Iterator
from typing import Any

class Range:
    @property
    def api(self) -> Any: ...
    @property
    def impl(self) -> Any: ...
    def __iter__(self) -> Iterator[Range]: ...
    def options(self, convert: type | None = None, **options: Any) -> Range: ...
    @property
    def sheet(self) -> Sheet: ...
    def __len__(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def row(self) -> int: ...
    @property
    def column(self) -> int: ...
    def end(self, direction: str) -> Range: ...
    def get_address(
        self,
        row_absolute: bool = True,
        column_absolute: bool = True,
        include_sheetname: bool = False,
        external: bool = False,
    ) -> str: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    def expand(self, mode: str = "table") -> Range: ...
    def __getitem__(self, key: Any) -> Range: ...
    def offset(self, row_offset: int = 0, column_offset: int = 0) -> Range: ...
    @property
    def last_cell(self) -> Range: ...

class Sheet:
    @property
    def api(self) -> Any: ...
    @property
    def impl(self) -> Any: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    def range(
        self,
        cell1: Range | tuple[int, int],
        cell2: Range | tuple[int, int],
    ) -> Range: ...
    @property
    def book(self) -> Book: ...

class Book:
    @property
    def name(self) -> str: ...
    @property
    def app(self) -> App: ...

class App:
    @property
    def api(self) -> Any: ...
    @property
    def screen_updating(self) -> bool: ...
    @screen_updating.setter
    def screen_updating(self, value: bool) -> None: ...

class Apps:
    @property
    def active(self) -> App: ...

class Books:
    @property
    def active(self) -> Book: ...

class Sheets:
    @property
    def active(self) -> Sheet: ...

class ActiveEngineApps(Apps): ...
class ActiveAppBooks(Books): ...
class ActiveBookSheets(Sheets): ...

apps: ActiveEngineApps
books: ActiveAppBooks
sheets: ActiveBookSheets
