import types
from collections.abc import Iterator
from typing import Any, Self

class Range:
    @property
    def api(self) -> Any: ...
    @property
    def impl(self) -> Any: ...
    def __iter__(self) -> Iterator[Range]: ...
    def options(self, convert: type | None = None, **options: Any) -> Range: ...
    @property
    def sheet(self) -> Sheet: ...
    def __len__(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def row(self) -> int: ...
    @property
    def column(self) -> int: ...
    def end(self, direction: str) -> Range: ...
    def get_address(
        self,
        row_absolute: bool = True,
        column_absolute: bool = True,
        include_sheetname: bool = False,
        external: bool = False,
    ) -> str: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    def expand(self, mode: str = "table") -> Range: ...
    def __getitem__(self, key: Any) -> Range: ...
    def offset(self, row_offset: int = 0, column_offset: int = 0) -> Range: ...
    @property
    def last_cell(self) -> Range: ...
    def autofit(self) -> None: ...
    @property
    def column_width(self) -> float: ...
    @column_width.setter
    def column_width(self, value: float) -> None: ...
    def merge(self, across: bool = False) -> None: ...
    @property
    def number_format(self) -> str: ...
    @number_format.setter
    def number_format(self, value: str) -> None: ...
    @property
    def formula(self) -> Any: ...
    @formula.setter
    def formula(self, value: Any) -> None: ...
    @property
    def left(self) -> float: ...
    @property
    def top(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...

class Sheet:
    @property
    def api(self) -> Any: ...
    @property
    def impl(self) -> Any: ...
    def __getitem__(self, item: Any) -> Range: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    def range(
        self,
        cell1: Range | tuple[int, int] | int | str,
        cell2: Range | tuple[int, int] | int | str | None = None,
    ) -> Range: ...
    @property
    def book(self) -> Book: ...
    @property
    def charts(self) -> Charts: ...
    def delete(self) -> None: ...
    def activate(self) -> None: ...

class Chart:
    @property
    def api(self) -> Any: ...
    @property
    def chart_type(self) -> str: ...
    @chart_type.setter
    def chart_type(self, value: str) -> None: ...
    @property
    def left(self) -> float: ...
    @left.setter
    def left(self, value: float) -> None: ...
    @property
    def top(self) -> float: ...
    @top.setter
    def top(self, value: float) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...

class Charts:
    def add(
        self,
        left: float = 0,
        top: float = 0,
        width: float = 355,
        height: float = 211,
    ) -> Chart: ...
    def __iter__(self) -> Iterator[Chart]: ...
    def __getitem__(self, key: Any) -> Chart: ...
    def __contains__(self, key: Any) -> bool: ...

class Book:
    @property
    def api(self) -> Any: ...
    @property
    def name(self) -> str: ...
    @property
    def app(self) -> App: ...
    @property
    def sheets(self) -> Sheets: ...
    def close(self) -> None: ...

class App:
    def __init__(self, visible: bool | None = None) -> None: ...
    @property
    def api(self) -> Any: ...
    @property
    def visible(self) -> bool: ...
    @visible.setter
    def visible(self, value: bool) -> None: ...
    @property
    def screen_updating(self) -> bool: ...
    @screen_updating.setter
    def screen_updating(self, value: bool) -> None: ...
    def quit(self) -> None: ...
    def kill(self) -> None: ...
    @property
    def books(self) -> Books: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...

class Apps:
    @property
    def active(self) -> App: ...
    def __iter__(self) -> Iterator[App]: ...

class Books:
    @property
    def active(self) -> Book: ...
    def add(self) -> Book: ...

class Sheets:
    @property
    def active(self) -> Sheet: ...
    def add(
        self,
        name: str | None = None,
        before: Sheet | None = None,
        after: Sheet | None = None,
    ) -> Sheet: ...
    def __getitem__(self, key: Any) -> Sheet: ...

class ActiveEngineApps(Apps): ...
class ActiveAppBooks(Books): ...
class ActiveBookSheets(Sheets): ...

apps: ActiveEngineApps
books: ActiveAppBooks
sheets: ActiveBookSheets
